### ISSUE TITLE
Failed to activate the ide-haskell-cabal package

### ISSUE THREAD

**Issue by known5** [atom-haskell/ide-haskell-cabal#22]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: [ide-haskell-cabal](https://github.com/atom-haskell/ide-haskell-cabal) package 2.2.0

### Stack Trace

Failed to activate the ide-haskell-cabal package

```
At Parameter ide-haskell-cabal.builder already defined!

Error: Parameter ide-haskell-cabal.builder already defined!
    at ConfigParamStore.addParamSpec (/packages/ide-haskell/lib/config-params/param-store.js:33:19)
    at ConfigParamManager.add (/packages/ide-haskell/lib/config-params/index.js:19:29)
    at Object.consume (/packages/ide-haskell/lib/upi-3/index.js:64:55)
    at Object.instance (/packages/ide-haskell/lib/upi-3/instance.js:12:24)
    at /packages/ide-haskell/lib/ide-haskell.js:106:21
    at /packages/ide-haskell-cabal/lib/ide-backend.js:60:20)
    at Object.consumeUPI (/packages/ide-haskell-cabal/lib/ide-haskell-cabal.js:19:21)
    at Provider.module.exports.Provider.provide (~/AppData/Local/atom/app-1.27.2/resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.consume (~/AppData/Local/atom/app-1.27.2/resources/app/node_modules/service-hub/lib/service-hub.js:50:24)
    at Package.activateServices (~/AppData/Local/atom/app-1.27.2/resources/app/src/package.js:405:79)
    at Package.activateNow (~/AppData/Local/atom/app-1.27.2/resources/app/src/package.js:233:20)
    at activationHookSubscriptions.add.packageManager.onDidTriggerActivationHook (~/AppData/Local/atom/app-1.27.2/resources/app/src/package.js:901:81)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.27.2/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.27.2/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at triggeredActivationHooks.forEach.hook (~/AppData/Local/atom/app-1.27.2/resources/app/src/package-manager.js:705:86)
    at Set.forEach (native)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.27.2/resources/app/src/package-manager.js:705:43)
    at packagesToEnable.forEach.name (~/AppData/Local/atom/app-1.27.2/resources/app/src/package-manager.js:440:51)
    at Array.forEach (native)
    at disabledPackagesSubscription.config.onDidChange (~/AppData/Local/atom/app-1.27.2/resources/app/src/package-manager.js:440:30)
    at emitter.on (~/AppData/Local/atom/app-1.27.2/resources/app/src/config.js:1067:22)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.27.2/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.27.2/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at Config.emitChangeEvent (~/AppData/Local/atom/app-1.27.2/resources/app/src/config.js:1226:62)
    at Config.setRawValue (~/AppData/Local/atom/app-1.27.2/resources/app/src/config.js:1052:23)
    at Config.set (~/AppData/Local/atom/app-1.27.2/resources/app/src/config.js:715:18)
    at Config.removeAtKeyPath (~/AppData/Local/atom/app-1.27.2/resources/app/src/config.js:905:16)
    at Package.enable (~/AppData/Local/atom/app-1.27.2/resources/app/src/package.js:75:30)
    at PackageManager.enablePackage (~/AppData/Local/atom/app-1.27.2/resources/app/src/package-manager.js:246:18)
    at HTMLButtonElement.enablementButtonClickHandler (~/AppData/Local/atom/app-1.27.2/resources/app/node_modules/settings-view/lib/package-card.js:362:31)
```

### Commands

```
     -8:52.4.0 ide-haskell:toggle-output (div.tool-panel.tree-view)
     -8:48.2.0 haskell-ghc-mod:lint-file (div.tool-panel.tree-view)
     -8:40.5.0 ide-haskell-cabal:set-build-target (div.tool-panel.tree-view)
  3x -8:37.2.0 core:backspace (input.hidden-input)
     -8:32.1.0 haskell-ghc-mod:check-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui.ide-haskell)
     -1:37 core:save (div.package-detail.panels-item)
     -0:38.3.0 haskell-ghc-mod:check-file (input#haskell-ghc-mod.enableGhcModi.input-checkbox)
```

### Non-Core Packages

```
autocomplete-haskell 1.0.1 
haskell-ghc-mod 2.2.3 
haskell-grammar 0.4.0 
ide-haskell 2.3.1 
ide-haskell-cabal 2.2.0 
language-haskell 1.17.8 
```

**Comment by lierdakil** [comment]
Hello! Thanks for your report. However, it's not really clear how to reproduce this. Generally speaking, this error can only happen if ide-haskell-cabal somehow activates *twice*, which shouldn't really be possible during normal operation. So a detailed reproduction guide would be very helpful.
