### ISSUE TITLE
IDE-Haskell-Cabal failed to get cabal-install version. Assuming cabal-install < 2.4

### ISSUE THREAD

**Issue by Yoshihiko-Ozaki** [atom-haskell/ide-haskell-cabal#27]
```
Atom: 1.60.0
OS: win32
Released: true
IDE-Haskell-Cabal: 2.6.1
IDE-Haskell: 2.7.0
Error Message: spawn cabal ENOENT
Error Stack:
Error: spawn cabal ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
Cabal output (if any):

PATH: 
System PATH: D:\Emacs-Program\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;D:\Emacs-Program\bin;C:\Program Files\Amazon Corretto\jdk18.0.1_10\bin;D:\app\tskwx\product\19.0.0\client_1\bin;C:\Program Files\Eclipse Adoptium\jdk-17.0.3.7-hotspot\bin;D:\app\client\tskwx\product\19.0.0\client_1\bin;C:\Program Files\Microsoft MPI\Bin;C:\ActiveTcl\bin;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\Python38\Scripts;C:\Program Files\Python38;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files\nodejs;C:\ProgramData\chocolatey\bin;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn;C:\Program Files\dotnet;C:\Program Files\CodeBlocks\MinGW\bin;C:\Program Files\Java\jdk-17.0.2\bin;C:\Strawberry\c\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Python310\Scripts;C:\ProgramData\chocolatey\lib\Elixir\bin;C:\Program Files\Java\jre7\bin;C:\Program Files (x86)\sbt\bin;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Emacs\x86_64\bin;C:\Program Files\Steel Bank Common Lisp;C:\Users\tskwx\OneDrive\画像\ドキュメント\platform-tools_r33.0.1-windows\platform-tools;C:\Prog;am Files\PowerShell\7;C:\Program Files\Git\cmd;C:\Program Files (x86)\dotnet;C:\Program Files\Java\jdk1.8.0_321\bin;C:\Progrram Files (x86)\Microsoft SQL Server\150\Tools\Binn;C:\Program Files\Azure Data Studio\bin;C:\Program Files\PowerShell\7;C:\Users\tskwx\AppData\Local\Programs\Julia-1.7.3\bin;C:\Users\tskwx\AppData\Local\atom\bin;C:\Program Files (x86)\Vim;C:\Program Files\Neovim\bin;C:\Users\tskwx\AppData\Roaming\local\bin;C:\Program Files (x86)\Haskell\bin;C:\ghc\ghc-7.0.1\bin;C:\Users\tskwx\anaconda3;C:\Users\tskwx\anaconda3\Library\mingw-w64\bin;C:\Users\tskwx\anaconda3\Library\usr\bin;C:\Users\tskwx\anaconda3\Library\bin;C:\Users\tskwx\anaconda3\Scripts;C:\Users\tskwx\scoop\apps\nodejs\current\bin;C:\Users\tskwx\scoop\apps\nodejs\current;C:\Users\tskwx\scoop\apps\perl\current\perl\site\bin;C:\Users\tskwx\scoop\apps\perl\current\perl\bin;C:\Users\tskwx\scoop\shims;C:\Users\tskwx\AppData\Local\activestate\cache\bin;C:\Users\tskwx\AppData\Local\ActiveState\StateTool\release;C:\Ruby31-x64\bin;C:\Users\tskwx\AppData\Local\Programs\Python\Python310\Scripts;C:\Users\tskwx\AppData\Local\Programs\Python\Python310;C:\Users\tskwx\AppData\Local\Microsoft\WindowsApps;C:\Users\tskwx\AppData\Roaming\npm;C:\Users\tskwx\.dotnet\tools;C:\cygwin64\bin;C:\Users\tskwx\AppData\Local\Programs\Microsoft VS Code Insiders\bin;C:\Users\tskwx\AppData\Local\GitHubDesktop\bin;C:\Program Files\JetBrains\P;C:\Users\tskwx\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\tskwx\AppData\Roaming\stack;C:\hie;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
```

**Comment by lierdakil** [comment]
You don't have cabal in PATH (or possibly at all).

Bear in mind this project is unmaintained and Atom is dead (it will be completely sunset by the end of this year)
