### ISSUE TITLE
Uncaught TypeError: path must be a string

### ISSUE THREAD

**Issue by rodrigovidal** [atom-haskell/ide-haskell-cabal#4]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.4
**Thrown From**: [ide-haskell-cabal](https://github.com/atom-haskell/ide-haskell-cabal) package, v0.1.1
### Stack Trace

Uncaught TypeError: path must be a string

```
At fs.js:813

TypeError: path must be a string
  at TypeError (native)
  at Object.fs.readdirSync (fs.js:813:18)
  at Object.fs.readdirSync (ATOM_SHELL_ASAR.js:449:28)
  at IdeBackend.module.exports.IdeBackend.containsCabalFile (/Users/rodrigovidal/.atom/packages/ide-haskell-cabal/lib/ide-backend.coffee:109:19)
  at IdeBackend.module.exports.IdeBackend.findCabalFile (/Users/rodrigovidal/.atom/packages/ide-haskell-cabal/lib/ide-backend.coffee:94:16)
  at IdeBackend.findCabalFile (/Users/rodrigovidal/.atom/packages/ide-haskell-cabal/lib/ide-backend.coffee:2:1)
  at IdeBackend.module.exports.IdeBackend.getTargets (/Users/rodrigovidal/.atom/packages/ide-haskell-cabal/lib/ide-backend.coffee:203:31)
  at PluginManager.setTarget (/Users/rodrigovidal/.atom/packages/ide-haskell/lib/plugin-manager.coffee:96:19)
  at PluginManager.setTarget (/Users/rodrigovidal/.atom/packages/ide-haskell/lib/plugin-manager.coffee:1:1)
  at atom-workspace.backendMenu.add.atom.commands.add.ide-haskell:set-build-target (/Users/rodrigovidal/.atom/packages/ide-haskell/lib/ide-haskell.coffee:347:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom 2.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom 2.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom 2.app/Contents/Resources/app.asar/src/command-registry.js:145:19)
  at HTMLElement.<anonymous> (/Users/rodrigovidal/.atom/packages/ide-haskell/lib/output-panel/views/output-panel.coffee:38:21)
  at HTMLElement.jQuery.event.dispatch (/Applications/Atom 2.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLElement.elemData.handle (/Applications/Atom 2.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```
### Commands

```
     -0:19.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:18.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:18.5.0 grammar-selector:show (atom-text-editor.editor)
     -0:17.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:06.5.0 ide-haskell:set-build-target (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "disabledPackages": [
      "image-view",
      "nuclide-file-tree"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
.bin, vundefined
atom-fsharp, v0.12.8
atom-html-preview, v0.1.11
atom-tsd, v0.9.0
atom-typescript, v7.4.1
atom-yeoman, vundefined
autocomplete-haskell, v0.5.1
autosave, v0.23.0
background-tips, v0.26.0
bookmarks, v0.38.0
browser-plus, v0.0.35
command-palette, v0.36.0
exception-reporting, v0.37.0
file-icons, v1.6.10
flex-tool-bar, v0.5.0
fuzzy-finder, v0.91.0
git-diff, v0.56.0
grammar-selector, v0.47.0
haskell-ghc-mod, v0.9.13
ide-haskell, v0.8.0
ide-haskell-cabal, v0.1.1
ionide-fake, v1.2.0
ionide-fsharp, v1.3.3
ionide-fsi, v1.0.8
ionide-installer, v1.3.0
ionide-paket, v2.2.0
ionide-webview, v1.0.0
ionide-yeoman, v1.0.1
json-schema, v0.1.15
keybinding-resolver, v0.33.0
language-elm, v1.2.0
language-haskell, v1.4.11
language-idris, v0.3.3
language-rust, v0.4.5
linter, v1.8.1
omnisharp-atom, v0.25.1
tool-bar, v0.1.9
tool-bar-main, v0.0.8
update-package-dependencies, v0.10.0

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
I have no idea how did you manage to get this. If it's not too much trouble, could you describe steps to reproduce this in detail? Only possibility I can fathom is you have no open files and no project directories...

**Comment by lierdakil** [comment]
Closing due to no response
