### ISSUE TITLE
Uncaught Error: ENOTDIR: not a directory, scandir 'C:\Users\deng\Desktop\Test.hs'

### ISSUE THREAD

**Issue by xdxxxdx** [atom-haskell/ide-haskell-cabal#6]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Unknown Windows Version
**Thrown From**: [ide-haskell-cabal](https://github.com/atom-haskell/ide-haskell-cabal) package, v1.0.0
### Stack Trace

Uncaught Error: ENOTDIR: not a directory, scandir 'C:\Users\deng\Desktop\Test.hs'

```
At fs.js:813

Error: ENOTDIR: not a directory, scandir 'C:\Users\deng\Desktop\Test.hs'
    at Error (native)
    at Object.fs.readdirSync (fs.js:813:18)
    at Object.fs.readdirSync (ATOM_SHELL_ASAR.js:449:28)
    at IdeBackend.module.exports.IdeBackend.containsCabalFile (file:///C:/Users/deng/.atom/packages/ide-haskell-cabal/lib/ide-backend.coffee:115:19)
    at IdeBackend.module.exports.IdeBackend.findCabalFile (file:///C:/Users/deng/.atom/packages/ide-haskell-cabal/lib/ide-backend.coffee:100:16)
    at IdeBackend.findCabalFile (file:///C:/Users/deng/.atom/packages/ide-haskell-cabal/lib/ide-backend.coffee:2:1)
    at IdeBackend.module.exports.IdeBackend.setTarget (file:///C:/Users/deng/.atom/packages/ide-haskell-cabal/lib/ide-backend.coffee:204:31)
    at atom-workspace.disposables.add.atom.commands.add.ide-haskell-cabal:set-build-target (file:///C:/Users/deng/.atom/packages/ide-haskell-cabal/lib/ide-haskell-cabal.coffee:44:17)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\deng\AppData\Local\atom\app-1.2.4\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\deng\AppData\Local\atom\app-1.2.4\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\deng\AppData\Local\atom\app-1.2.4\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\deng\AppData\Local\atom\app-1.2.4\resources\app.asar\src\atom-environment.js:987:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```
### Commands

```
 27x -4:27.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:02.3.0 haskell-ghc-mod:check-file (atom-notification.error.icon.icon-flame.native-key-bindings.has-detail.has-close)
     -3:59.9.0 haskell-ghc-mod:shutdown-backend (atom-notification.error.icon.icon-flame.native-key-bindings.has-detail.has-close)
  9x -3:58.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:10.5.0 ide-haskell-cabal:set-build-target (atom-notification.error.icon.icon-flame.native-key-bindings.has-detail.has-close)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-haskell, v0.6.2
haskell-ghc-mod, v1.2.0
haskell-grammar, v0.4.0
haskell-pointfree, v0.1.2
haskell-unicode-snippets, v0.1.0
ide-haskell, v1.3.6
ide-haskell-cabal, v1.0.0
ide-haskell-repl, v0.0.4
language-haskell, v1.5.1

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
I'll have to ask you to describe steps for reproduction. It is not immediately obvious, to say the least.

**Comment by lierdakil** [comment]
Closing due to no response.
