### ISSUE TITLE
Uncaught Error: Unkown builder '[object Object]'

### ISSUE THREAD

**Issue by ssgreg** [atom-haskell/ide-haskell-cabal#9]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [ide-haskell-cabal](https://github.com/atom-haskell/ide-haskell-cabal) package, v1.3.1
### Stack Trace

Uncaught Error: Unkown builder '[object Object]'

```
At /Users/igreg/.atom/packages/ide-haskell-cabal/lib/ide-backend.coffee:104

Error: Unkown builder '[object Object]'
    at IdeBackend.module.exports.IdeBackend.cabalBuild (/Users/igreg/.atom/packages/ide-haskell-cabal/lib/ide-backend.coffee:104:19)
    at IdeBackend.cabalBuild (/Users/igreg/.atom/packages/ide-haskell-cabal/lib/ide-backend.coffee:2:1)
    at IdeBackend.module.exports.IdeBackend.build (/Users/igreg/.atom/packages/ide-haskell-cabal/lib/ide-backend.coffee:160:6)
    at atom-workspace.disposables.add.atom.commands.add.ide-haskell-cabal:build (/Users/igreg/.atom/packages/ide-haskell-cabal/lib/ide-haskell-cabal.coffee:64:17)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1100:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:314:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```
### Commands

```
     -0:00.5.0 ide-haskell-cabal:build (atom-text-editor.editor.is-focused)
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
autocomplete-haskell, v0.6.5
haskell-ghc-mod, v1.12.2
ide-haskell, v1.6.3
ide-haskell-cabal, v1.3.1
language-haskell, v1.7.15

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
Thanks for reporting. Should be fixed in 1.3.2
